# -*- coding: utf-8 -*-
"""sentiment_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sc8x-0Kr3o1hhS_gYVTdW6jExxli5jcs
"""

import pickle
import pandas as pd
import streamlit as st

# Load the trained pipeline model
with open('pipeline_model.pkl', 'rb') as f:
    pipeline = pickle.load(f)

# Function to predict sentiment
def predict_sentiment(text):
    # Create a DataFrame with the text
    df = pd.DataFrame({'text': [text]})
    # Perform prediction
    prediction = pipeline.predict(df['text'])[0]
    # Map prediction value to sentiment label
    sentiment = "Positive" if prediction == 1 else "Negative"

    return sentiment

# Streamlit app
def main():
    st.title("Sentiment Analyser")

    # Input text box for user input
    text = st.text_area("Enter text to analyze sentiment:")

    # Predict button
    if st.button("Predict"):
        # Check if text is empty
        if not text:
            st.error("Please enter text to analyze sentiment.")
        else:
            # Call predict_sentiment function to get sentiment label
            sentiment = predict_sentiment(text)
            # Display sentiment label
            st.write("Sentiment:", sentiment)

if __name__ == "__main__":
    main()